[package]
name = "btc"
version = "0.1.0"
edition = "2024"

[dependencies]
secp256k1 = { version = "0.30.0", default-features = false, features = ["hashes", "alloc"] }
bitcoin = "0.30"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true