[workspace]
members = [ 
  "btc",
  "eth",
]
resolver = "2"


[workspace.dependencies]
tokio = { version = "1.28.1", features = ["full"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = { version = "0.10", default-features = false }
